version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo123
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
